### PR TITLE
rename to @nextcloud/eslint-config

### PR DESCRIPTION
**Pull request by korelstar**
Breaking change! This requires all apps using this package to be updated to the new name!

Also, I've already changed URLs for repository, homepage and bugs to https://github.com/nextcloud/eslint-config/ -- therefore, this repository has to be renamed immediately.

### CODE REVIEW

**Comment by ChristophWurst** [comment]
> Breaking change! This requires all apps using this package to be updated to the new name!

We can deprecate the old package once there is a new one.

**Comment by ChristophWurst** [comment]
> this repository has to be renamed immediately.

done

**Comment by korelstar** [comment]
Would you mind to create a new release, then? :smiley:

**Comment by ChristophWurst** [comment]
Published & deprecated the old one!

**Pull request merged**
