### PR TITLE
Update @babel/core @babel/eslint-parser eslint-config-standard eslint…

### PR DESCRIPTION
**Pull request by skjnldsv**
…-plugin-import eslint-plugin-promise and webpack

But not eslint 8: https://github.com/nextcloud/eslint-config/issues/230

### CODE REVIEW

**Comment by artonge** [comment]
Might be better to keep webpack under `5.48.0`. [As said](https://github.com/nextcloud/backup/pull/29#discussion_r742079065) webpack >= `5.48.0` breaks probably most of our Node CI because we want reproducible sourcemaps and [this workaround](https://github.com/webpack/webpack/issues/3603=) does not work anymore.

I opened [this PR](https://github.com/webpack/webpack/pull/14628) but I am really not sure about the content...

**Review by Pytal — APPROVED** [review]
Other than the breaking webpack minor, should be good 🚀

**Comment by Pytal** [comment]
Did not know that this repo allows just one approval 🤷‍♂️

**Comment by Pytal** [comment]
Did not know that this repo allows just one approval, hope no one accidently merges this

**Comment by Pytal** [comment]
Did not know that this repo allows just one approval, hope no one accidently merges before downgrade

**Comment by Pytal** [comment]
Did not know that this repo allows just one approval, hope no one accidently merges before downgrade 🤞

**Pull request closed without merging**
