### PR TITLE
remove eslint-plugin-standard

### LINKED ISSUE #101: Is eslint-plugin-standard still necessary as peerDependency?
See https://github.com/standard/standard/issues/1316

### PR DESCRIPTION
**Pull request by dartcafe**
fix #101

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by dartcafe** [comment]
@skjnldsv How are the rules, does the author of the PR the merge after review or someone like a release manager?

**Comment by skjnldsv** [comment]
You can merge :)

**Comment by skjnldsv** [comment]
Then you edit the CHANGELOG, and tag a new release with npm version and push --tags

**Comment by dartcafe** [comment]
@skjnldsv Hope, I did as expected. BTW: 5.0.0 changelog is missing. 😉

**Comment by skjnldsv** [comment]
> Hmmm. I guess, I did somethin wrong. I tried to push the changelog and the version update to the master branch, but is was rejected (understandable). ~As a result the package has a wrong version number (still 5.0.0)~

You should have done the changelog before the npm version.
Then you need to push the commit straight to master.
Or create a pr and once it's merged, create a release tagging the current master.

But creating a release automatically compile and publish the release to npm :see_no_evil:

**Comment by dartcafe** [comment]
I changed the changelog and did an `npm version minor` followed by push --tags. Trying to push to the master branch was rejected (no access?). Therefore I created #111. 

The release package here is created from the tag and contains version 5.1.0. The package on npm still countains version 5.0.0.

**Comment by dartcafe** [comment]
> But creating a release automatically compile and publish the release to npm 🙈

Yes. Learned that now... 😉

**Comment by skjnldsv** [comment]
> The package on npm still countains version 5.0.0

Time to merge and release 5.1.1 :see_no_evil:

**Comment by dartcafe** [comment]
> Time to merge and release 5.1.1

Who? Me? Serious???? I don't grant for anything. 🤣

**Pull request merged**
