### PR TITLE
Fix resolving packages that use the package `exports` feature

### PR DESCRIPTION
**Pull request by susnux**
Required for packages that make use of the `exports` features, as the `eslint-plugin-import` relays on `browserify/resolve` for resolving packages which does not support the `exports` feature (supported by Node 12.7+).

(usage example: import the `gettext` module from the  `l10n` package)

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
Wanna release v8.2.1 ?

**Comment by susnux** [comment]
> Wanna release v8.2.1 ?

I would highly appreciate that :)

**Comment by skjnldsv** [comment]
appreciate you doing the release or me? xD

**Comment by susnux** [comment]
You, I do not think I have the permission level for creating release^^

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/eslint-config/pull/453

**Pull request merged**
